version:  '3.7'
services:
  server:
    build: .
    restart: always
    ports:
      - 9090:8080
    depends_on:
      - mysqldb

  mysqldb:
    platform: linux/arm64/v8
    restart: always
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=employee
      - MYSQL_USER=aditya
      - MYSQL_PASSWORD=password